### ISSUE TITLE
tkey-react-native-firebase-example get error on android when click login with web3auth ( ios work well )

### ISSUE THREAD

**Issue by vukhaihoan** [Web3Auth/web3auth-core-kit-examples#70]
![Screenshot 2023-05-16 at 13 25 18](https://github.com/Web3Auth/web3auth-core-kit-examples/assets/58582870/1c3622ce-f7ca-4d9d-9375-a9e4e8d4b283)

**Comment by yashovardhan** [comment]
Hey @vukhaihoan we're aware about this issue and are working towards fixing that. For any questions, please follow up on https://community.web3auth.io

Thank you!
